# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/configure/yaml/

# A 'specific' Stackage snapshot or a compiler version.
snapshot: lts-23.3

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the snapshot.
extra-deps:
- git: https://github.com/symtegration/symtegration
  commit: '9e199ebfc7ab804c9eed04ec253556c0a6a811cf'
