# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/configure/yaml/

# A 'specific' Stackage snapshot or a compiler version.
snapshot: nightly-2025-02-01

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the snapshot.
extra-deps:
- symtegration-0.6.1
